# Generated by Django 4.2.7 on 2023-11-30 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todoitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='todo_list',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
