# Generated by Django 4.2.7 on 2023-12-01 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_remove_todoitem_todo_list_delete_todolist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoItem',
            new_name='Task',
        ),
    ]
